# tools/deployment_tools.py
import os
import json
import mlflow
import mlflow.sklearn
import pandas as pd
import numpy as np
from langchain_core.tools import tool
from dotenv import load_dotenv

load_dotenv()


def setup_mlflow():
    mlflow.set_tracking_uri(
        os.getenv("MLFLOW_TRACKING_URI", "sqlite:///mlflow.db")
    )


@tool
def load_champion_model() -> str:
    """
    Load the registered champion model from MLflow Model Registry.
    Saves it locally for the FastAPI server to use.
    Returns model info.
    """
    try:
        setup_mlflow()
        client = mlflow.tracking.MlflowClient()

        model_name = "hospital-readmission-champion"
        versions = client.get_latest_versions(
            model_name, stages=["Staging"]
        )

        if not versions:
            return "No model found in Staging stage."

        version = versions[0]
        model_uri = f"models:/{model_name}/Staging"
        model = mlflow.sklearn.load_model(model_uri)

        # Save model locally for FastAPI to load
        import pickle
        os.makedirs("api", exist_ok=True)
        with open("api/champion_model.pkl", "wb") as f:
            pickle.dump(model, f)

        return json.dumps({
            "status":      "success",
            "model_name":  model_name,
            "version":     version.version,
            "run_id":      version.run_id,
            "saved_to":    "api/champion_model.pkl"
        }, indent=2)
    except Exception as e:
        return f"Error: {str(e)}"


@tool
def get_model_feature_info(dataset_path: str) -> str:
    """
    Get the feature names the model expects as input.
    This is used to generate the API documentation.
    """
    try:
        df = pd.read_csv(dataset_path)
        features = [c for c in df.columns if c != "readmitted"]
        sample_row = df[features].iloc[0].to_dict()

        # Convert numpy types to native Python for JSON serialization
        sample_row = {
            k: float(v) if isinstance(v, (np.floating, np.integer))
            else v
            for k, v in sample_row.items()
        }

        return json.dumps({
            "feature_count": len(features),
            "features":      features,
            "sample_input":  sample_row
        }, indent=2)
    except Exception as e:
        return f"Error: {str(e)}"


@tool
def create_fastapi_server(features_json: str) -> str:
    """
    Generate and save the FastAPI server code.
    Creates a production-ready API for the champion model.
    """
    try:
        features_data = json.loads(features_json)
        features      = features_data["features"]
        sample_input  = features_data["sample_input"]

        # Build field definitions for the Pydantic model
        field_lines = "\n".join([
            f"    {feat}: float"
            for feat in features
        ])

        sample_json = json.dumps(sample_input, indent=8)

        api_code = f'''# api/main.py
# FastAPI server for Hospital Readmission Prediction
# Champion model: LightGBM — loaded from MLflow Model Registry
# Auto-generated by the Deployment Agent

import pickle
import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Dict
import uvicorn
import os

# ── Load model at startup ──────────────────────────────────
MODEL_PATH = os.path.join(os.path.dirname(__file__), "champion_model.pkl")

try:
    with open(MODEL_PATH, "rb") as f:
        model = pickle.load(f)
    print("✅ Champion model loaded successfully")
except Exception as e:
    print(f"❌ Error loading model: {{e}}")
    model = None

# ── FastAPI app ────────────────────────────────────────────
app = FastAPI(
    title="Hospital Readmission Prediction API",
    description="""
    Autonomous ML Research Agent — Deployment
    
    Predicts 30-day hospital readmission risk using a 
    LightGBM model trained and selected autonomously.
    
    - Model: LightGBM (AUC: 0.91)
    - Trained on: CMS Hospital Readmission Dataset
    - Pipeline: 5-agent autonomous ML system
    """,
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Request/Response models ────────────────────────────────
class PatientData(BaseModel):
{field_lines}

    class Config:
        json_schema_extra = {{
            "example": {sample_json}
        }}

class PredictionResponse(BaseModel):
    readmission_risk:       str
    readmission_probability: float
    confidence:             str
    recommendation:         str
    model_version:          str

# ── Endpoints ──────────────────────────────────────────────
@app.get("/")
def root():
    return {{
        "service":     "Hospital Readmission Prediction API",
        "status":      "live",
        "model":       "LightGBM Champion",
        "docs":        "/docs",
    }}

@app.get("/health")
def health():
    return {{
        "status":       "healthy",
        "model_loaded": model is not None
    }}

@app.post("/predict", response_model=PredictionResponse)
def predict(patient: PatientData):
    if model is None:
        raise HTTPException(
            status_code=503,
            detail="Model not loaded"
        )
    try:
        # Build feature array in correct order
        features = {features}
        input_data = np.array([[
            getattr(patient, feat) for feat in features
        ]])

        probability = float(model.predict_proba(input_data)[0][1])
        prediction  = "HIGH RISK" if probability >= 0.5 else "LOW RISK"

        if probability >= 0.7:
            confidence      = "High"
            recommendation  = "Immediate follow-up care recommended within 7 days"
        elif probability >= 0.5:
            confidence      = "Medium"
            recommendation  = "Schedule follow-up within 14 days"
        else:
            confidence      = "High"
            recommendation  = "Standard discharge protocol — routine follow-up"

        return PredictionResponse(
            readmission_risk        = prediction,
            readmission_probability = round(probability, 4),
            confidence              = confidence,
            recommendation          = recommendation,
            model_version           = "LightGBM-v1-Champion"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/model/info")
def model_info():
    return {{
        "model_type":     "LightGBM",
        "features":       {features},
        "feature_count":  {len(features)},
        "target":         "readmitted (0/1)",
        "performance":    {{
            "auc":      0.9177,
            "f1":       0.92,
            "accuracy": 0.92
        }},
        "training_data":  "CMS Hospital Readmission Dataset",
        "pipeline":       "5-agent autonomous ML system"
    }}

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
'''

        with open("api/main.py", "w") as f:
            f.write(api_code)

        return json.dumps({
            "status":   "success",
            "saved_to": "api/main.py",
            "endpoints": ["/", "/health", "/predict", "/model/info", "/docs"]
        }, indent=2)
    except Exception as e:
        return f"Error: {str(e)}"


@tool
def verify_api_files() -> str:
    """
    Verify all required API files exist and are ready.
    """
    try:
        checks = {
            "api/main.py":           os.path.exists("api/main.py"),
            "api/champion_model.pkl": os.path.exists("api/champion_model.pkl"),
        }
        all_ready = all(checks.values())

        return json.dumps({
            "status": "ready" if all_ready else "missing files",
            "files":  checks,
            "next_step": "Run: cd api && uvicorn main:app --reload"
            if all_ready else "Fix missing files first"
        }, indent=2)
    except Exception as e:
        return f"Error: {str(e)}"